/*
 * cuda_solver.cu — GPU-Accelerated Rubik's Cube Solver
 *
 * Root-cause fix: PDB was generated by converting index→54 facelets (filling
 * non-corner positions with the sentinel value 6), then calling gpu_apply
 * (which shuffles those 6s into corner slots), then re-hashing — producing
 * completely wrong neighbour distances.
 *
 * Fix: generate PDB purely in (cp[8], co[8]) space using hard-coded corner
 * cycle tables, never touching the 54-facelet representation.
 */

#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <Python.h>

#define N_MOVES            18
#define MAX_DEPTH          22
#define MAX_SWAPS_PER_MOVE 15
#define FRONTIER_DEPTH     6
#define MAX_FRONTIER       4000000
#define PDB_SIZE           88179840   // 8! × 3^7

typedef struct { uint8_t f[54]; } Cube;
typedef struct {
    uint8_t  state[54];
    uint16_t perm_idx;
    uint16_t ori_idx;
    int      path[FRONTIER_DEPTH];
} FrontierNode;

// ─── MOVE TABLE (54-facelet swaps) ───────────────────────────────────────────

static const int h_move_swaps[N_MOVES][MAX_SWAPS_PER_MOVE][2] = {
    {{0,2},{0,8},{0,6},{1,5},{1,7},{1,3},{9,18},{9,36},{9,45},{10,19},{10,37},{10,46},{11,20},{11,38},{11,47}},
    {{0,6},{0,8},{0,2},{1,3},{1,7},{1,5},{9,45},{9,36},{9,18},{10,46},{10,37},{10,19},{11,47},{11,38},{11,20}},
    {{0,8},{1,7},{2,6},{3,5},{9,36},{10,37},{11,38},{18,45},{19,46},{20,47},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}},
    {{15,51},{15,42},{15,24},{16,52},{16,43},{16,25},{17,53},{17,44},{17,26},{27,29},{27,35},{27,33},{28,32},{28,34},{28,30}},
    {{15,24},{15,42},{15,51},{16,25},{16,43},{16,52},{17,26},{17,44},{17,53},{27,33},{27,35},{27,29},{28,30},{28,34},{28,32}},
    {{15,42},{16,43},{17,44},{24,51},{25,52},{26,53},{27,35},{28,34},{29,33},{30,32},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}},
    {{2,51},{2,29},{2,20},{5,48},{5,32},{5,23},{8,45},{8,35},{8,26},{9,11},{9,17},{9,15},{10,14},{10,16},{10,12}},
    {{2,20},{2,29},{2,51},{5,23},{5,32},{5,48},{8,26},{8,35},{8,45},{9,15},{9,17},{9,11},{10,12},{10,16},{10,14}},
    {{2,29},{5,32},{8,35},{9,17},{10,16},{11,15},{12,14},{20,51},{23,48},{26,45},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}},
    {{0,18},{0,27},{0,53},{3,21},{3,30},{3,50},{6,24},{6,33},{6,47},{36,38},{36,44},{36,42},{37,41},{37,43},{37,39}},
    {{0,53},{0,27},{0,18},{3,50},{3,30},{3,21},{6,47},{6,33},{6,24},{36,42},{36,44},{36,38},{37,39},{37,43},{37,41}},
    {{0,27},{3,30},{6,33},{18,53},{21,50},{24,47},{36,44},{37,43},{38,42},{39,41},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}},
    {{6,9},{6,29},{6,44},{7,12},{7,28},{7,41},{8,15},{8,27},{8,38},{18,20},{18,26},{18,24},{19,23},{19,25},{19,21}},
    {{6,44},{6,29},{6,9},{7,41},{7,28},{7,12},{8,38},{8,27},{8,15},{18,24},{18,26},{18,20},{19,21},{19,25},{19,23}},
    {{6,29},{7,28},{8,27},{9,44},{12,41},{15,38},{18,26},{19,25},{20,24},{21,23},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}},
    {{0,42},{0,35},{0,11},{1,39},{1,34},{1,14},{2,36},{2,33},{2,17},{45,47},{45,53},{45,51},{46,50},{46,52},{46,48}},
    {{0,11},{0,35},{0,42},{1,14},{1,34},{1,39},{2,17},{2,33},{2,36},{45,51},{45,53},{45,47},{46,48},{46,52},{46,50}},
    {{0,35},{1,34},{2,33},{11,42},{14,39},{17,36},{45,53},{46,52},{47,51},{48,50},{-1,-1},{-1,-1},{-1,-1},{-1,-1},{-1,-1}}
};

static const char* MOVE_NAMES[N_MOVES] = {
    "U","U'","U2","D","D'","D2","R","R'","R2","L","L'","L2","F","F'","F2","B","B'","B2"
};

__constant__ int d_move_swaps[N_MOVES][MAX_SWAPS_PER_MOVE][2];
__constant__ int d_FACT[8] = {1,1,2,6,24,120,720,5040};
static const int h_FACT[8] = {1,1,2,6,24,120,720,5040};

__device__ int d_found_flag = 0;
__device__ int d_found_path[MAX_DEPTH];

// ─── 54-FACELET MOVE APPLY ───────────────────────────────────────────────────

static void cpu_apply(Cube* c, int m) {
    for (int s = 0; s < MAX_SWAPS_PER_MOVE; s++) {
        int a = h_move_swaps[m][s][0], b = h_move_swaps[m][s][1];
        if (a < 0) break;
        uint8_t t = c->f[a]; c->f[a] = c->f[b]; c->f[b] = t;
    }
}

static inline int cpu_get_inverse(int m) {
    int mod = m % 3;
    if (mod == 0) return m + 1;
    if (mod == 1) return m - 1;
    return m;
}

__device__ inline void gpu_apply(uint8_t* f, int m) {
    for (int s = 0; s < MAX_SWAPS_PER_MOVE; s++) {
        int a = d_move_swaps[m][s][0], b = d_move_swaps[m][s][1];
        if (a < 0) break;
        uint8_t t = f[a]; f[a] = f[b]; f[b] = t;
    }
}

__device__ inline int gpu_get_inverse(int m) {
    int mod = m % 3;
    if (mod == 0) return m + 1;
    if (mod == 1) return m - 1;
    return m; // x2 is self-inverse
}

static int cpu_solved(const Cube* c) {
    for (int face = 0; face < 6; face++)
        for (int i = 0; i < 9; i++)
            if (c->f[face*9+i] != (uint8_t)face) return 0;
    return 1;
}

__device__ int gpu_solved(const uint8_t* f) {
    for (int face = 0; face < 6; face++)
        for (int i = 0; i < 9; i++)
            if (f[face*9+i] != (uint8_t)face) return 0;
    return 1;
}

// ─── CORNER COORDINATE ───────────────────────────────────────────────────────
//
// Corner slot layout (kociemba standard):
//   0:URF  1:UFL  2:ULB  3:UBR  4:DFR  5:DLF  6:DBL  7:DRB
//
// For each slot the three facelet positions are listed as
//   (UD-facelet, CW-facelet-1, CW-facelet-2)
// In the solved state facelet j has color j/9.
//
// Piece identity: determined by the SET of 3 colors.
// Orientation   : which position holds the U(0) or D(3) color.
//   ori=0 → UD color is at position [0]
//   ori=1 → UD color is at position [1]
//   ori=2 → UD color is at position [2]

static const int h_CF[8][3] = {
    { 8, 9,20},   // slot 0 URF  solved colors {0,1,2}
    { 6,18,38},   // slot 1 UFL  solved colors {0,2,4}
    { 0,36,47},   // slot 2 ULB  solved colors {0,4,5}
    { 2,45,11},   // slot 3 UBR  solved colors {0,5,1}
    {29,26,15},   // slot 4 DFR  solved colors {3,2,1}
    {27,44,24},   // slot 5 DLF  solved colors {3,4,2}
    {33,53,42},   // slot 6 DBL  solved colors {3,5,4}
    {35,17,51}    // slot 7 DRB  solved colors {3,1,5}
};

// Home color sets per piece (sorted ascending) — used to identify piece from colors
// piece 0:{0,1,2} piece 1:{0,2,4} piece 2:{0,4,5} piece 3:{0,1,5}
// piece 4:{1,2,3} piece 5:{2,3,4} piece 6:{3,4,5} piece 7:{1,3,5}
static const uint8_t PIECE_COLORS[8][3] = {
    {0,1,2},{0,2,4},{0,4,5},{0,1,5},
    {1,2,3},{2,3,4},{3,4,5},{1,3,5}
};

static int find_piece(uint8_t a, uint8_t b, uint8_t c) {
    // sort
    uint8_t t;
    if (a>b){t=a;a=b;b=t;} if (b>c){t=b;b=c;c=t;} if (a>b){t=a;a=b;b=t;}
    for (int i=0;i<8;i++)
        if (PIECE_COLORS[i][0]==a && PIECE_COLORS[i][1]==b && PIECE_COLORS[i][2]==c) return i;
    return 0;
}

// Encode (cp[8], co[8]) as a single uint32 index in [0, PDB_SIZE)
static inline uint32_t encode_corners(const uint8_t* cp, const uint8_t* co) {
    uint32_t perm = 0;
    for (int i=0;i<7;i++){
        int cnt=0; for(int j=i+1;j<8;j++) if(cp[j]<cp[i]) cnt++;
        perm += cnt * h_FACT[7-i];
    }
    uint32_t ori=0; for(int i=0;i<7;i++) ori=ori*3+co[i];
    return perm*2187+ori;
}

// Split encode: perm only → Lehmer code in [0, 40320)
static inline uint16_t encode_perm(const uint8_t* cp) {
    uint32_t perm = 0;
    for (int i=0;i<7;i++){
        int cnt=0; for(int j=i+1;j<8;j++) if(cp[j]<cp[i]) cnt++;
        perm += cnt * h_FACT[7-i];
    }
    return (uint16_t)perm;
}

// Split encode: ori only → base-3 code in [0, 2187)
static inline uint16_t encode_ori(const uint8_t* co) {
    uint32_t ori=0; for(int i=0;i<7;i++) ori=ori*3+co[i];
    return (uint16_t)ori;
}

// Decode Lehmer code → permutation
static void decode_perm(uint16_t perm_code, uint8_t* cp) {
    uint8_t avail[8] = {0,1,2,3,4,5,6,7};
    int n_avail = 8;
    uint32_t p = perm_code;
    for (int i = 0; i < 7; i++) {
        int digit = p / h_FACT[7 - i];
        p %= h_FACT[7 - i];
        cp[i] = avail[digit];
        n_avail--;
        for (int j = digit; j < n_avail; j++) avail[j] = avail[j+1];
    }
    cp[7] = avail[0];
}

// Decode base-3 code → orientation
static void decode_ori(uint16_t ori_code, uint8_t* co) {
    int co_sum = 0;
    uint32_t o = ori_code;
    for (int i = 6; i >= 0; i--) {
        co[i] = (uint8_t)(o % 3);
        co_sum += co[i];
        o /= 3;
    }
    co[7] = (uint8_t)((3 - co_sum % 3) % 3);
}

// Extract (cp, co) from 54-facelet state
static void extract_corners_cpu(const uint8_t* f, uint8_t* cp, uint8_t* co) {
    for (int i=0;i<8;i++){
        uint8_t c0=f[h_CF[i][0]], c1=f[h_CF[i][1]], c2=f[h_CF[i][2]];
        cp[i] = (uint8_t)find_piece(c0,c1,c2);
        if      (c0==0||c0==3) co[i]=0;
        else if (c1==0||c1==3) co[i]=1;
        else                    co[i]=2;
    }
}

// Same thing usable on GPU — inline, reads from __constant__ d_CF
__constant__ int d_CF[8][3] = {
    { 8, 9,20},{ 6,18,38},{ 0,36,47},{ 2,45,11},
    {29,26,15},{27,44,24},{33,53,42},{35,17,51}
};
__constant__ uint8_t d_PIECE_COLORS[8][3] = {
    {0,1,2},{0,2,4},{0,4,5},{0,1,5},
    {1,2,3},{2,3,4},{3,4,5},{1,3,5}
};

__device__ static int d_find_piece(uint8_t a,uint8_t b,uint8_t c){
    uint8_t t;
    if(a>b){t=a;a=b;b=t;} if(b>c){t=b;b=c;c=t;} if(a>b){t=a;a=b;b=t;}
    for(int i=0;i<8;i++)
        if(d_PIECE_COLORS[i][0]==a&&d_PIECE_COLORS[i][1]==b&&d_PIECE_COLORS[i][2]==c) return i;
    return 0;
}

__device__ static uint32_t gpu_corner_index(const uint8_t* f){
    uint8_t cp[8],co[8];
    for(int i=0;i<8;i++){
        uint8_t c0=f[d_CF[i][0]],c1=f[d_CF[i][1]],c2=f[d_CF[i][2]];
        cp[i]=(uint8_t)d_find_piece(c0,c1,c2);
        if(c0==0||c0==3) co[i]=0;
        else if(c1==0||c1==3) co[i]=1;
        else co[i]=2;
    }
    uint32_t perm=0;
    for(int i=0;i<7;i++){
        int cnt=0; for(int j=i+1;j<8;j++) if(cp[j]<cp[i]) cnt++;
        perm+=cnt*d_FACT[7-i];
    }
    uint32_t ori=0; for(int i=0;i<7;i++) ori=ori*3+co[i];
    return perm*2187+ori;
}

// ─── GPU CORNER APPLY (fast path: avoids 54-facelet extraction) ──────────────

__constant__ int d_CORNER_CYCLE[6][4] = {
    {0,1,2,3},{4,7,6,5},{0,3,7,4},{1,5,6,2},{0,4,5,1},{2,6,7,3}
};
__constant__ int d_CORNER_ORI_DELTA[6][4] = {
    {0,0,0,0},{0,0,0,0},{1,2,1,2},{2,1,2,1},{2,1,2,1},{2,1,2,1}
};

__device__ inline void gpu_apply_corners(uint8_t* cp, uint8_t* co, int m) {
    int face=m/3, mod=m%3;
    int sa=d_CORNER_CYCLE[face][0], sb=d_CORNER_CYCLE[face][1];
    int sc=d_CORNER_CYCLE[face][2], sd=d_CORNER_CYCLE[face][3];
    uint8_t pa=cp[sa],pb=cp[sb],pc=cp[sc],pd=cp[sd];
    uint8_t oa=co[sa],ob=co[sb],oc=co[sc],od=co[sd];
    if(mod==2){
        cp[sa]=pc;cp[sb]=pd;cp[sc]=pa;cp[sd]=pb;
        co[sa]=oc;co[sb]=od;co[sc]=oa;co[sd]=ob;
    } else if(mod==0){
        cp[sb]=pa;cp[sc]=pb;cp[sd]=pc;cp[sa]=pd;
        co[sb]=(oa+d_CORNER_ORI_DELTA[face][0])%3;
        co[sc]=(ob+d_CORNER_ORI_DELTA[face][1])%3;
        co[sd]=(oc+d_CORNER_ORI_DELTA[face][2])%3;
        co[sa]=(od+d_CORNER_ORI_DELTA[face][3])%3;
    } else {
        cp[sd]=pa;cp[sc]=pd;cp[sb]=pc;cp[sa]=pb;
        co[sd]=(oa+(3-d_CORNER_ORI_DELTA[face][3]))%3;
        co[sc]=(od+(3-d_CORNER_ORI_DELTA[face][2]))%3;
        co[sb]=(oc+(3-d_CORNER_ORI_DELTA[face][1]))%3;
        co[sa]=(ob+(3-d_CORNER_ORI_DELTA[face][0]))%3;
    }
}

__device__ inline uint32_t gpu_encode_corners(const uint8_t* cp, const uint8_t* co) {
    uint32_t perm=0;
    for(int i=0;i<7;i++){
        int cnt=0; for(int j=i+1;j<8;j++) if(cp[j]<cp[i]) cnt++;
        perm+=cnt*d_FACT[7-i];
    }
    uint32_t ori=0; for(int i=0;i<7;i++) ori=ori*3+co[i];
    return perm*2187+ori;
}

// ─── PDB GENERATION (CPU BFS in cp/co space) ─────────────────────────────────
//
// We work entirely in (cp[8],co[8]) — no 54-facelet representation needed.
// Corner permutation cycles and orientation deltas for each move,
// derived from kociemba standard with verified slot numbering:
//
//  Slots:  0:URF  1:UFL  2:ULB  3:UBR  4:DFR  5:DLF  6:DBL  7:DRB
//
// Each face move is a 4-cycle of corner slots.
// CW cycle a→b→c→d means: after move, slot b gets piece that was in a, etc.
// Orientation delta: add to co of the piece AFTER it moves (mod 3).
// U and D moves don't twist corners.  R,L,F,B twist by alternating +1/+2.

// [face][slot_a, slot_b, slot_c, slot_d]  — CW 4-cycle: a→b→c→d→a
static const int CORNER_CYCLE[6][4] = {
    {0,1,2,3}, // U: URF→UFL→ULB→UBR
    {4,7,6,5}, // D: DFR→DRB→DBL→DLF
    {0,3,7,4}, // R: URF→UBR→DRB→DFR
    {1,5,6,2}, // L: UFL→DLF→DBL→ULB
    {0,4,5,1}, // F: URF→DFR→DLF→UFL
    {2,6,7,3}, // B: ULB→DBL→DRB→UBR
};

static const int CORNER_ORI_DELTA[6][4] = {
    {0,0,0,0}, // U
    {0,0,0,0}, // D
    {1,2,1,2}, // R
    {2,1,2,1}, // L
    {2,1,2,1}, // F
    {2,1,2,1}, // B
};

// Apply move m to (cp,co) in-place
static void apply_corners_cpu(uint8_t* cp, uint8_t* co, int m) {
    int face = m/3, mod = m%3;
    const int* cyc = CORNER_CYCLE[face];
    const int* od  = CORNER_ORI_DELTA[face];

    int a=cyc[0],b=cyc[1],c=cyc[2],d=cyc[3];
    uint8_t ocp[8],oco[8];
    for(int i=0;i<8;i++){ocp[i]=cp[i];oco[i]=co[i];}

    if (mod==2) {
        // half turn: swap pairs, no orientation change
        cp[a]=ocp[c]; cp[b]=ocp[d]; cp[c]=ocp[a]; cp[d]=ocp[b];
        co[a]=oco[c]; co[b]=oco[d]; co[c]=oco[a]; co[d]=oco[b];
    } else if (mod==0) {
        // CW: a→b→c→d (slot b receives piece from a, etc.)
        cp[b]=ocp[a]; cp[c]=ocp[b]; cp[d]=ocp[c]; cp[a]=ocp[d];
        co[b]=(oco[a]+od[0])%3; co[c]=(oco[b]+od[1])%3;
        co[d]=(oco[c]+od[2])%3; co[a]=(oco[d]+od[3])%3;
    } else {
        // CCW: a→d→c→b
        cp[d]=ocp[a]; cp[c]=ocp[d]; cp[b]=ocp[c]; cp[a]=ocp[b];
        co[d]=(oco[a]+(3-od[3]))%3; co[c]=(oco[d]+(3-od[2]))%3;
        co[b]=(oco[c]+(3-od[1]))%3; co[a]=(oco[b]+(3-od[0]))%3;
    }
}

static uint8_t* g_corner_pdb = NULL;

// ─── PRE-COMPUTED MOVE TABLES ────────────────────────────────────────────────
//
// perm_move[m][p] = new perm index after applying move m to perm index p
// ori_move[m][o]  = new ori  index after applying move m to ori  index o
//
// These replace the per-node apply_corners + encode_corners with a single
// table lookup each, cutting the hot-path cost dramatically.

static uint16_t h_perm_move[N_MOVES][40320];
static uint16_t h_ori_move[N_MOVES][2187];

static void generate_move_tables() {
    fprintf(stderr, "[cuda_solver] Generating move tables...\n");
    for (int m = 0; m < N_MOVES; m++) {
        int face = m/3, mod = m%3;
        const int* cyc = CORNER_CYCLE[face];
        int a=cyc[0],b=cyc[1],c=cyc[2],d=cyc[3];

        for (uint32_t p = 0; p < 40320; p++) {
            uint8_t cp[8], ncp[8];
            decode_perm((uint16_t)p, cp);
            for(int i=0;i<8;i++) ncp[i]=cp[i];
            if (mod==2) {
                ncp[a]=cp[c]; ncp[b]=cp[d]; ncp[c]=cp[a]; ncp[d]=cp[b];
            } else if (mod==0) {
                ncp[b]=cp[a]; ncp[c]=cp[b]; ncp[d]=cp[c]; ncp[a]=cp[d];
            } else {
                ncp[d]=cp[a]; ncp[c]=cp[d]; ncp[b]=cp[c]; ncp[a]=cp[b];
            }
            h_perm_move[m][p] = encode_perm(ncp);
        }

        const int* od = CORNER_ORI_DELTA[face];
        for (uint32_t o = 0; o < 2187; o++) {
            uint8_t co[8], nco[8];
            decode_ori((uint16_t)o, co);
            for(int i=0;i<8;i++) nco[i]=co[i];
            if (mod==2) {
                nco[a]=co[c]; nco[b]=co[d]; nco[c]=co[a]; nco[d]=co[b];
            } else if (mod==0) {
                nco[b]=(co[a]+od[0])%3; nco[c]=(co[b]+od[1])%3;
                nco[d]=(co[c]+od[2])%3; nco[a]=(co[d]+od[3])%3;
            } else {
                nco[d]=(co[a]+(3-od[3]))%3; nco[c]=(co[d]+(3-od[2]))%3;
                nco[b]=(co[c]+(3-od[1]))%3; nco[a]=(co[b]+(3-od[0]))%3;
            }
            h_ori_move[m][o] = encode_ori(nco);
        }
    }
    fprintf(stderr, "[cuda_solver] Move tables ready.\n");
}

// Decode a PDB index back to (cp[8], co[8])
static void decode_corners(uint32_t idx, uint8_t* cp, uint8_t* co) {
    uint32_t ori_code = idx % 2187;
    uint32_t perm_code = idx / 2187;

    // Decode orientation (base 3 for first 7; 8th is determined by sum≡0 mod 3)
    int co_sum = 0;
    for (int i = 6; i >= 0; i--) {
        co[i] = (uint8_t)(ori_code % 3);
        co_sum += co[i];
        ori_code /= 3;
    }
    co[7] = (uint8_t)((3 - co_sum % 3) % 3);

    // Decode permutation from Lehmer code (factorial number system)
    uint8_t avail[8] = {0,1,2,3,4,5,6,7};
    int n_avail = 8;
    for (int i = 0; i < 7; i++) {
        int digit = perm_code / h_FACT[7 - i];
        perm_code %= h_FACT[7 - i];
        cp[i] = avail[digit];
        n_avail--;
        for (int j = digit; j < n_avail; j++) avail[j] = avail[j+1];
    }
    cp[7] = avail[0];
}

// BFS-based PDB generation: scan PDB at each depth, expand neighbors
static void generate_pdb_cpu() {
    g_corner_pdb = (uint8_t*)malloc(PDB_SIZE);
    if (!g_corner_pdb) { fprintf(stderr,"[cuda_solver] OOM\n"); exit(1); }

    // Try loading from disk cache
    const char* cache_path = "corner_pdb.bin";
    FILE* cf = fopen(cache_path, "rb");
    if (cf) {
        size_t n = fread(g_corner_pdb, 1, PDB_SIZE, cf);
        fclose(cf);
        if ((int)n == PDB_SIZE) {
            // Verify PDB is fully generated (no 255 entries should remain)
            int has_unfilled = 0;
            for (uint32_t i = 0; i < PDB_SIZE && !has_unfilled; i++)
                if (g_corner_pdb[i] == 255) has_unfilled = 1;
            if (!has_unfilled) {
                fprintf(stderr, "[cuda_solver] PDB loaded from cache (%s).\n", cache_path);
                return;
            }
            fprintf(stderr, "[cuda_solver] Cache incomplete, regenerating...\n");
        } else {
            fprintf(stderr, "[cuda_solver] Cache corrupt, regenerating...\n");
        }
    }

    fprintf(stderr, "[cuda_solver] Building 84MB Corner PDB (one-time, will cache to %s)...\n", cache_path);
    memset(g_corner_pdb, 255, PDB_SIZE);

    g_corner_pdb[0] = 0;  // solved state → index 0 → distance 0

    long long total = 1;
    for (int d = 0; d < 12; d++) {
        long long new_count = 0;
        for (uint32_t idx = 0; idx < (uint32_t)PDB_SIZE; idx++) {
            if (g_corner_pdb[idx] != (uint8_t)d) continue;

            uint16_t pi = (uint16_t)(idx / 2187);
            uint16_t oi = (uint16_t)(idx % 2187);

            for (int m = 0; m < N_MOVES; m++) {
                uint32_t nidx = (uint32_t)h_perm_move[m][pi] * 2187 + h_ori_move[m][oi];
                if (g_corner_pdb[nidx] == 255) {
                    g_corner_pdb[nidx] = (uint8_t)(d + 1);
                    new_count++;
                }
            }
        }
        total += new_count;
        fprintf(stderr, "  PDB depth %d: %lld new states (total %lld / %d)\n",
                d + 1, new_count, total, PDB_SIZE);

        if (new_count == 0 || total >= (long long)PDB_SIZE) break;
    }

    // Save to disk
    FILE* out2 = fopen(cache_path, "wb");
    if (out2) { fwrite(g_corner_pdb, 1, PDB_SIZE, out2); fclose(out2); }
    fprintf(stderr, "[cuda_solver] PDB complete and saved to %s.\n", cache_path);
}

// ─── CORNER INDEX FROM 54-FACELET STATE ──────────────────────────────────────

static uint32_t cpu_corner_index(const uint8_t* f) {
    uint8_t cp[8], co[8];
    extract_corners_cpu(f, cp, co);
    return encode_corners(cp, co);
}

// ─── GPU IDA* KERNEL ─────────────────────────────────────────────────────────

__global__ void kernel_ida_search(
    FrontierNode* nodes, int num_nodes, int max_depth, const uint8_t* pdb,
    const uint16_t* perm_tbl, const uint16_t* ori_tbl
) {
    int tid = blockIdx.x*blockDim.x+threadIdx.x;
    if (tid>=num_nodes||d_found_flag) return;

    FrontierNode node = nodes[tid];
    uint8_t state[54];
    for(int i=0;i<54;i++) state[i]=node.state[i];

    int path[MAX_DEPTH];
    int move_idx[MAX_DEPTH];
    uint16_t pstk[MAX_DEPTH+1];
    uint16_t ostk[MAX_DEPTH+1];
    for(int i=0;i<FRONTIER_DEPTH;i++) path[i]=node.path[i];
    pstk[FRONTIER_DEPTH] = node.perm_idx;
    ostk[FRONTIER_DEPTH] = node.ori_idx;

    int depth=FRONTIER_DEPTH;
    move_idx[FRONTIER_DEPTH]=0;

    while(depth>=FRONTIER_DEPTH){
        if(d_found_flag) return;

        if(depth==max_depth){
            if(gpu_solved(state)){
                if(atomicCAS(&d_found_flag,0,1)==0)
                    for(int i=0;i<max_depth;i++) d_found_path[i]=path[i];
            }
            depth--;
            if(depth>=FRONTIER_DEPTH){
                gpu_apply(state,gpu_get_inverse(path[depth]));
            }
            continue;
        }

        int m=move_idx[depth];
        if(m>=N_MOVES){
            depth--;
            if(depth>=FRONTIER_DEPTH){
                gpu_apply(state,gpu_get_inverse(path[depth]));
            }
            continue;
        }
        move_idx[depth]++;

        int face=m/3;
        int last_face=(depth>0)?path[depth-1]/3:-1;
        if(face==last_face) continue;
        if(last_face>=0 && face==(last_face^1) && face>last_face) continue;

        uint16_t np = __ldg(&perm_tbl[m * 40320 + pstk[depth]]);
        uint16_t no = __ldg(&ori_tbl[m * 2187 + ostk[depth]]);
        uint32_t cidx = (uint32_t)np * 2187 + no;
        if((depth+1)+(int)pdb[cidx]<=max_depth){
            gpu_apply(state,m);
            path[depth]=m;
            pstk[depth+1]=np;
            ostk[depth+1]=no;
            depth++;
            move_idx[depth]=0;
        }
    }
}

// ─── HOST SOLVE LOGIC ────────────────────────────────────────────────────────

static uint8_t*      d_corner_pdb    = NULL;
static uint16_t*     d_perm_move     = NULL;
static uint16_t*     d_ori_move      = NULL;
static FrontierNode* h_frontier      = NULL;
static int           h_frontier_count = 0;
static int           g_found         = 0;
static int           g_path[MAX_DEPTH];

static void init_pdb() {
    if (g_corner_pdb) return;
    generate_move_tables();
    generate_pdb_cpu();
    cudaMalloc(&d_corner_pdb, PDB_SIZE);
    cudaMemcpy(d_corner_pdb, g_corner_pdb, PDB_SIZE, cudaMemcpyHostToDevice);
    cudaMalloc(&d_perm_move, 18 * 40320 * sizeof(uint16_t));
    cudaMemcpy(d_perm_move, h_perm_move, 18 * 40320 * sizeof(uint16_t), cudaMemcpyHostToDevice);
    cudaMalloc(&d_ori_move, 18 * 2187 * sizeof(uint16_t));
    cudaMemcpy(d_ori_move, h_ori_move, 18 * 2187 * sizeof(uint16_t), cudaMemcpyHostToDevice);
    h_frontier = (FrontierNode*)malloc(MAX_FRONTIER * sizeof(FrontierNode));
    fprintf(stderr,"[cuda_solver] PDB + move tables uploaded to GPU.\n");
}

static void dfs_cpu(Cube* state, uint16_t perm_idx, uint16_t ori_idx, int depth, int max_depth, int last_face, int* path) {
    if (g_found) return;
    uint32_t cidx = (uint32_t)perm_idx * 2187 + ori_idx;
    if (depth + (int)g_corner_pdb[cidx] > max_depth) return;
    if (depth==max_depth){
        if (cpu_solved(state)){
            memcpy(g_path,path,max_depth*sizeof(int));
            g_found=1;
        }
        return;
    }
    for(int m=0;m<N_MOVES;m++){
        int face=m/3;
        if(face==last_face) continue;
        if(last_face>=0 && face==(last_face^1) && face>last_face) continue;
        uint16_t np = h_perm_move[m][perm_idx];
        uint16_t no = h_ori_move[m][ori_idx];
        uint32_t ncidx = (uint32_t)np * 2187 + no;
        if ((depth+1) + (int)g_corner_pdb[ncidx] > max_depth) continue;
        path[depth]=m;
        cpu_apply(state,m);
        dfs_cpu(state,np,no,depth+1,max_depth,face,path);
        cpu_apply(state,cpu_get_inverse(m));
        if(g_found) return;
    }
}

static void generate_frontier(Cube* state, uint16_t perm_idx, uint16_t ori_idx, int depth, int max_depth, int last_face, int* path) {
    uint32_t cidx = (uint32_t)perm_idx * 2187 + ori_idx;
    if (depth + (int)g_corner_pdb[cidx] > max_depth) return;
    if (depth==FRONTIER_DEPTH){
        if (h_frontier_count<MAX_FRONTIER){
            FrontierNode n;
            for(int i=0;i<54;i++) n.state[i]=state->f[i];
            n.perm_idx=perm_idx;
            n.ori_idx=ori_idx;
            for(int i=0;i<FRONTIER_DEPTH;i++) n.path[i]=path[i];
            h_frontier[h_frontier_count++]=n;
        }
        return;
    }
    for(int m=0;m<N_MOVES;m++){
        int face=m/3;
        if(face==last_face) continue;
        if(last_face>=0 && face==(last_face^1) && face>last_face) continue;
        path[depth]=m;
        cpu_apply(state,m);
        uint16_t np = h_perm_move[m][perm_idx];
        uint16_t no = h_ori_move[m][ori_idx];
        generate_frontier(state,np,no,depth+1,max_depth,face,path);
        cpu_apply(state,cpu_get_inverse(m));
    }
}

// ─── PARSE ───────────────────────────────────────────────────────────────────

static int parse_cube(const char* s, Cube* c) {
    if (strlen(s)!=54) return 0;
    const char* fc="URFDLB";
    for(int i=0;i<54;i++){
        const char* p=strchr(fc,s[i]);
        if(!p) return 0;
        c->f[i]=(uint8_t)(p-fc);
    }
    return 1;
}

// ─── PYTHON API ──────────────────────────────────────────────────────────────

static PyObject* py_solve(PyObject* self, PyObject* args) {
    const char* cube_str;
    if(!PyArg_ParseTuple(args,"s",&cube_str)) return NULL;

    Cube cube;
    if(!parse_cube(cube_str,&cube)){
        PyErr_SetString(PyExc_ValueError,"invalid cube string (need 54 URFDLB chars)");
        return NULL;
    }

    init_pdb();

    if(cpu_solved(&cube)) return PyUnicode_FromString("");

    uint8_t cp[8], co[8];
    extract_corners_cpu(cube.f, cp, co);
    uint16_t perm_idx = encode_perm(cp);
    uint16_t ori_idx  = encode_ori(co);
    int start_depth=(int)g_corner_pdb[(uint32_t)perm_idx * 2187 + ori_idx];
    if(start_depth==0) start_depth=1;

    for(int d=start_depth;d<=MAX_DEPTH;d++){
        g_found=0;

        if(d<=FRONTIER_DEPTH){
            fprintf(stderr,"[cuda_solver] Depth %d (CPU IDA*)...\n",d);
            int path[MAX_DEPTH];
            dfs_cpu(&cube,perm_idx,ori_idx,0,d,-1,path);
        } else {
            h_frontier_count=0;
            int path[MAX_DEPTH];
            generate_frontier(&cube,perm_idx,ori_idx,0,d,-1,path);
            fprintf(stderr,"[cuda_solver] Depth %d — %d frontier nodes (GPU)...\n",d,h_frontier_count);

            if(h_frontier_count>0){
                FrontierNode* d_frontier;
                cudaMalloc(&d_frontier,h_frontier_count*sizeof(FrontierNode));
                cudaMemcpy(d_frontier,h_frontier,h_frontier_count*sizeof(FrontierNode),cudaMemcpyHostToDevice);

                int zero=0;
                cudaMemcpyToSymbol(d_found_flag,&zero,sizeof(int));

                int chunk=200000;
                int total=(h_frontier_count+chunk-1)/chunk;
                for(int i=0;i<h_frontier_count&&!g_found;i+=chunk){
                    fprintf(stderr,"\r  chunk %d/%d...",i/chunk+1,total);
                    int cur=(i+chunk>h_frontier_count)?(h_frontier_count-i):chunk;
                    kernel_ida_search<<<(cur+255)/256,256>>>(d_frontier+i,cur,d,d_corner_pdb,d_perm_move,d_ori_move);
                    cudaDeviceSynchronize();
                    cudaMemcpyFromSymbol(&g_found,d_found_flag,sizeof(int));
                }
                fprintf(stderr,"\n");
                if(g_found)
                    cudaMemcpyFromSymbol(g_path,d_found_path,d*sizeof(int));
                cudaFree(d_frontier);
            }
        }

        if(g_found){
            char res[256]={0};
            for(int i=0;i<d;i++){
                if(i) strcat(res," ");
                strcat(res,MOVE_NAMES[g_path[i]]);
            }
            return PyUnicode_FromString(res);
        }
    }

    PyErr_SetString(PyExc_RuntimeError,"No solution found within MAX_DEPTH");
    return NULL;
}

static PyObject* py_health(PyObject* self, PyObject* args){
    int n=0; cudaGetDeviceCount(&n);
    return PyLong_FromLong(n);
}

static PyMethodDef Methods[]={
    {"solve", py_solve, METH_VARARGS,"Solve cube."},
    {"health",py_health,METH_VARARGS,"CUDA device count."},
    {NULL,NULL,0,NULL}
};

static struct PyModuleDef module={
    PyModuleDef_HEAD_INIT,"cuda_solver",NULL,-1,Methods
};

PyMODINIT_FUNC PyInit_cuda_solver(){
    cudaMemcpyToSymbol(d_move_swaps,h_move_swaps,sizeof(h_move_swaps));
    return PyModule_Create(&module);
}
